//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name foreign from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VNDToForeignCurrencies", ReplyAction="*")]
        WebApplication1.ServiceReference1.VNDToForeignCurrenciesResponse VNDToForeignCurrencies(WebApplication1.ServiceReference1.VNDToForeignCurrenciesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VNDToForeignCurrencies", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.VNDToForeignCurrenciesResponse> VNDToForeignCurrenciesAsync(WebApplication1.ServiceReference1.VNDToForeignCurrenciesRequest request);
        
        // CODEGEN: Generating message contract since element name foreign from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ForeignCurrenciesToVND", ReplyAction="*")]
        WebApplication1.ServiceReference1.ForeignCurrenciesToVNDResponse ForeignCurrenciesToVND(WebApplication1.ServiceReference1.ForeignCurrenciesToVNDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ForeignCurrenciesToVND", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.ForeignCurrenciesToVNDResponse> ForeignCurrenciesToVNDAsync(WebApplication1.ServiceReference1.ForeignCurrenciesToVNDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VNDToForeignCurrenciesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VNDToForeignCurrencies", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.ServiceReference1.VNDToForeignCurrenciesRequestBody Body;
        
        public VNDToForeignCurrenciesRequest() {
        }
        
        public VNDToForeignCurrenciesRequest(WebApplication1.ServiceReference1.VNDToForeignCurrenciesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VNDToForeignCurrenciesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string foreign;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double vnd;
        
        public VNDToForeignCurrenciesRequestBody() {
        }
        
        public VNDToForeignCurrenciesRequestBody(string foreign, double vnd) {
            this.foreign = foreign;
            this.vnd = vnd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VNDToForeignCurrenciesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VNDToForeignCurrenciesResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.ServiceReference1.VNDToForeignCurrenciesResponseBody Body;
        
        public VNDToForeignCurrenciesResponse() {
        }
        
        public VNDToForeignCurrenciesResponse(WebApplication1.ServiceReference1.VNDToForeignCurrenciesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VNDToForeignCurrenciesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double VNDToForeignCurrenciesResult;
        
        public VNDToForeignCurrenciesResponseBody() {
        }
        
        public VNDToForeignCurrenciesResponseBody(double VNDToForeignCurrenciesResult) {
            this.VNDToForeignCurrenciesResult = VNDToForeignCurrenciesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ForeignCurrenciesToVNDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ForeignCurrenciesToVND", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.ServiceReference1.ForeignCurrenciesToVNDRequestBody Body;
        
        public ForeignCurrenciesToVNDRequest() {
        }
        
        public ForeignCurrenciesToVNDRequest(WebApplication1.ServiceReference1.ForeignCurrenciesToVNDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ForeignCurrenciesToVNDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string foreign;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double money;
        
        public ForeignCurrenciesToVNDRequestBody() {
        }
        
        public ForeignCurrenciesToVNDRequestBody(string foreign, double money) {
            this.foreign = foreign;
            this.money = money;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ForeignCurrenciesToVNDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ForeignCurrenciesToVNDResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.ServiceReference1.ForeignCurrenciesToVNDResponseBody Body;
        
        public ForeignCurrenciesToVNDResponse() {
        }
        
        public ForeignCurrenciesToVNDResponse(WebApplication1.ServiceReference1.ForeignCurrenciesToVNDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ForeignCurrenciesToVNDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double ForeignCurrenciesToVNDResult;
        
        public ForeignCurrenciesToVNDResponseBody() {
        }
        
        public ForeignCurrenciesToVNDResponseBody(double ForeignCurrenciesToVNDResult) {
            this.ForeignCurrenciesToVNDResult = ForeignCurrenciesToVNDResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WebApplication1.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WebApplication1.ServiceReference1.WebService1Soap>, WebApplication1.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ServiceReference1.VNDToForeignCurrenciesResponse WebApplication1.ServiceReference1.WebService1Soap.VNDToForeignCurrencies(WebApplication1.ServiceReference1.VNDToForeignCurrenciesRequest request) {
            return base.Channel.VNDToForeignCurrencies(request);
        }
        
        public double VNDToForeignCurrencies(string foreign, double vnd) {
            WebApplication1.ServiceReference1.VNDToForeignCurrenciesRequest inValue = new WebApplication1.ServiceReference1.VNDToForeignCurrenciesRequest();
            inValue.Body = new WebApplication1.ServiceReference1.VNDToForeignCurrenciesRequestBody();
            inValue.Body.foreign = foreign;
            inValue.Body.vnd = vnd;
            WebApplication1.ServiceReference1.VNDToForeignCurrenciesResponse retVal = ((WebApplication1.ServiceReference1.WebService1Soap)(this)).VNDToForeignCurrencies(inValue);
            return retVal.Body.VNDToForeignCurrenciesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.VNDToForeignCurrenciesResponse> WebApplication1.ServiceReference1.WebService1Soap.VNDToForeignCurrenciesAsync(WebApplication1.ServiceReference1.VNDToForeignCurrenciesRequest request) {
            return base.Channel.VNDToForeignCurrenciesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.VNDToForeignCurrenciesResponse> VNDToForeignCurrenciesAsync(string foreign, double vnd) {
            WebApplication1.ServiceReference1.VNDToForeignCurrenciesRequest inValue = new WebApplication1.ServiceReference1.VNDToForeignCurrenciesRequest();
            inValue.Body = new WebApplication1.ServiceReference1.VNDToForeignCurrenciesRequestBody();
            inValue.Body.foreign = foreign;
            inValue.Body.vnd = vnd;
            return ((WebApplication1.ServiceReference1.WebService1Soap)(this)).VNDToForeignCurrenciesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ServiceReference1.ForeignCurrenciesToVNDResponse WebApplication1.ServiceReference1.WebService1Soap.ForeignCurrenciesToVND(WebApplication1.ServiceReference1.ForeignCurrenciesToVNDRequest request) {
            return base.Channel.ForeignCurrenciesToVND(request);
        }
        
        public double ForeignCurrenciesToVND(string foreign, double money) {
            WebApplication1.ServiceReference1.ForeignCurrenciesToVNDRequest inValue = new WebApplication1.ServiceReference1.ForeignCurrenciesToVNDRequest();
            inValue.Body = new WebApplication1.ServiceReference1.ForeignCurrenciesToVNDRequestBody();
            inValue.Body.foreign = foreign;
            inValue.Body.money = money;
            WebApplication1.ServiceReference1.ForeignCurrenciesToVNDResponse retVal = ((WebApplication1.ServiceReference1.WebService1Soap)(this)).ForeignCurrenciesToVND(inValue);
            return retVal.Body.ForeignCurrenciesToVNDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.ForeignCurrenciesToVNDResponse> WebApplication1.ServiceReference1.WebService1Soap.ForeignCurrenciesToVNDAsync(WebApplication1.ServiceReference1.ForeignCurrenciesToVNDRequest request) {
            return base.Channel.ForeignCurrenciesToVNDAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.ForeignCurrenciesToVNDResponse> ForeignCurrenciesToVNDAsync(string foreign, double money) {
            WebApplication1.ServiceReference1.ForeignCurrenciesToVNDRequest inValue = new WebApplication1.ServiceReference1.ForeignCurrenciesToVNDRequest();
            inValue.Body = new WebApplication1.ServiceReference1.ForeignCurrenciesToVNDRequestBody();
            inValue.Body.foreign = foreign;
            inValue.Body.money = money;
            return ((WebApplication1.ServiceReference1.WebService1Soap)(this)).ForeignCurrenciesToVNDAsync(inValue);
        }
    }
}
